### ISSUE TITLE
Joining CoolCoder

### ISSUE THREAD

**Issue by zmontgo** [DUTIdevelopment/WIZARD.CSS#20]
Dear @benjaminbhollon ,
We are interested in your project. As of now, we have cloned it to our projects page. If you wish to make that the default branch, we would be very happy about that. Please consider doing so, as we foresee this being a significant help to your project, as we gather more and more developers to help us with our projects.
Thank you,
Zachary and the CoolCoder Team

**Comment by benjaminbhollon** [comment]
Your organization may help by forking the project, but we are keeping it here at our organization.
